use global vars to fasten up parent runner scripts
mozziemozz/M365CallFlowVisualizer pull request #34
Opened 2022-12-30 10:13 UTC by MicheleBomello

2022-12-30 19:08 UTC, mozziemozz requested changes
Thanks for the PR. Would you mind putting the if statements onto separate lines, like I've done it with all the other if statements? I want to maintain my formatting style. I hope you can understand. Thanks.

2023-01-09 06:24 UTC, MicheleBomello commented
> Thanks for the PR. Would you mind putting the if statements onto separate lines, like I've done it with all the other if statements? I want to maintain my formatting style. I hope you can understand. Thanks.

of course I understand that 😉. done.

2023-01-19 20:17 UTC, mozziemozz approved these changes

2023-01-19 20:18 UTC, merged

2023-01-19 20:23 UTC, mozziemozz commented
Thank you @MicheleBomello for contributing to my project. I've pushed your changes to the main branch aswell.